# Generated by Django 6.0.6 on 2026-06-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notes_on_activity',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('on_hold', 'On Hold'), ('blocked', 'Blocked')], default='working', max_length=100),
        ),
    ]
