# Generated by Django 6.0.6 on 2026-06-15 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='optc_sys.customer'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='optc_sys.product'),
        ),
    ]
