# Generated by Django 6.0.6 on 2026-06-24 18:20

import django.db.models.deletion
import django.utils.timezone
import optc_sys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0003_remove_saleitem_sale_remove_saleitem_product_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pickup_date',
            field=models.DateTimeField(default=optc_sys.models.get_five_days_from_now_at_eight_pm),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='optc_sys.prescription'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_name',
            field=models.CharField(blank=True, default='need name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(blank=True, default='need type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='pickup_date',
            field=models.DateTimeField(default=optc_sys.models.get_five_days_from_now_at_eight_pm),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_type',
            field=models.CharField(choices=[('r', 'Reading'), ('d', 'Distance')], default='need categorization', max_length=30),
        ),
    ]
