# Generated by Django 6.0.6 on 2026-06-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0004_invoice_pickup_date_invoice_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='item_source',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
