# Generated by Django 6.0.6 on 2026-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0005_invoiceitem_item_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensdetails',
            name='lens_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lensdetails',
            name='lens_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
