# Generated by Django 6.0.6 on 2026-06-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0006_lensdetails_lens_color_lensdetails_lens_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('lens', 'Lens'), ('repairs', 'Repairs'), ('other', 'Other')], max_length=20),
        ),
    ]
