# Generated by Django 6.0.6 on 2026-06-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0007_invoice_seller_alter_invoiceitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='optc_sys.product'),
        ),
    ]
