# Generated by Django 6.0.6 on 2026-07-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0008_alter_invoiceitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=100, null=True)),
                ('item_color', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_received', models.BooleanField(default=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='optc_sys.invoiceitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_type', models.CharField(choices=[('optical_lens', 'Optical Lens'), ('contact_lens', 'Contact Lens')], max_length=30)),
                ('sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lens_usage', models.CharField(blank=True, max_length=255, null=True)),
                ('lens_color', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_received', models.BooleanField(default=False)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_lens', to='optc_sys.invoiceitem')),
            ],
        ),
    ]
