# Generated by Django 6.0.6 on 2026-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0009_orderitem_orderlens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_source',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('order', 'Order'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('lens', 'Lens'), ('repairs', 'Repairs'), ('other', 'Other'), ('contact_lens', 'Contact Lens'), ('accessory', 'Accessory')], max_length=20),
        ),
    ]
