# Generated by Django 6.0.6 on 2026-07-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optc_sys', '0011_invoice_paid_amount_invoice_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frame_category',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('sunglasses', 'Sunglasses')], max_length=50, null=True),
        ),
    ]
